version = '0.11.0'

[[files."CHANGELOG.md"]]
search = '''
## [Unreleased] ##
'''
replace = '''
## [Unreleased] ##

## [{{new_version}}] - {{utcnow | strftime('%Y-%m-%d')}} ##
'''

[[files."CHANGELOG.md"]]
search = '''
[Unreleased]: https://github.com/dochang/mb-url/compare/{{old_version}}...HEAD
'''
replace = '''
[Unreleased]: https://github.com/dochang/mb-url/compare/{{new_version}}...HEAD
[{{new_version}}]: https://github.com/dochang/mb-url/compare/{{old_version}}...{{new_version}}
'''

[[files."mb-url.el"]]
search = '{{old_version}}'
replace = '{{new_version}}'

[[files."README.md"]]
search = '{{old_version}}'
replace = '{{new_version}}'

[[files."Cask"]]
search = '{{old_version}}'
replace = '{{new_version}}'
