APPLY_FIXES: none
SHOW_ELAPSED_TIME: true
IGNORE_GITIGNORED_FILES: true
DISABLE:
  - SPELL
FILEIO_REPORTER: true
DISABLE_LINTERS:
  - REPOSITORY_DEVSKIM
REPOSITORY_DEVSKIM_ARGUMENTS: --ignore-globs .github/workflows/ci.yml
# We use internal container to serve http mock server and we are unable to
# exclude all CI files which contain `http://localhost` because of the
# following error:
#
# Specify --help for a list of available options and commands.
# Unhandled exception. Microsoft.Extensions.CommandLineUtils.CommandParsingException: Unexpected value '**/megalinter-reports/**' for option 'ignore-globs'
#    at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
#    at Microsoft.DevSkim.CLI.Program.Main(String[] args) in D:\a\1\s\DevSkim-DotNet\Microsoft.DevSkim.CLI\Program.cs:line 14
#
# So just disable DevSkim.
