version: 2.1

jobs:
  MegaLinter:
    docker:
      - image: oxsecurity/megalinter:v8
        # checkov:skip=CKV_CIRCLECIPIPELINES_2:prefer mutable but stable tags
    steps:
      - checkout
      - run:
          name: Setup environment variables
          command: |
            echo "export CI_JOB_URL=$CIRCLE_BUILD_URL" >> "$BASH_ENV"
            # Export `CI_JOB_URL` for MegaLinter API Reporter
            echo "export DEFAULT_WORKSPACE=$CIRCLE_WORKING_DIRECTORY" >> "$BASH_ENV"
            . "$BASH_ENV"
      - run:
          name: Run MegaLinter
          command: |
            sh /entrypoint.sh
      - store_artifacts:
          path: megalinter-reports
  test:
    parameters:
      emacs-version:
        type: string
    docker:
      - image: silex/emacs:<< parameters.emacs-version >>-ci-eldev
        # checkov:skip=CKV_CIRCLECIPIPELINES_2:prefer mutable but stable tags
      - image: mccutchen/go-httpbin
        # checkov:skip=CKV_CIRCLECIPIPELINES_2:prefer mutable but stable tags
    steps:
      - checkout
      - run:
          name: Install homebrew
          command: |
            apt-get update && apt-get --yes install build-essential procps curl file git
            # https://github.com/orgs/Homebrew/discussions/3030
            bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          environment:
            NONINTERACTIVE: 1
      - restore_cache:
          keys:
            - &eldev-cache-key v1-eldev-<< parameters.emacs-version >>-{{ checksum "Eldev" }}
            - v1-eldev-<< parameters.emacs-version >>-
            - v1-eldev-
      - run:
          name: Test
          command: |
            eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
            brew bundle install
            dockerize -wait "${MB_URL_TEST__MOCKAPI_PREFIX}" -timeout 60s
            # Waiting for mock server
            eldev lint
            eldev test
          environment:
            MB_URL_TEST__MOCKAPI_PREFIX: "http://localhost:8080"
            HOMEBREW_BUNDLE_NO_LOCK: 1
          no_output_timeout: 5m
      - save_cache:
          key: *eldev-cache-key
          paths:
            - "~/.cache/eldev"

workflows:
  CI:
    jobs:
      - MegaLinter:
          context: megalinter
      - test:
          matrix:
            parameters:
              emacs-version:
                - "27.1"
                - "27.2"
                - "28.1"
                - "28.2"
                - "29.1"
                - "29.2"
                - "29.3"
                - "29.4"
                - "30.1"
          context: test
